services:
  - type: web
    name: srisrinivasa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free  # Explicitly specify free tier
    # Enable WebSocket support (critical for real-time updates)
    properties:
      websockets: true
